/**
 * config.ts — Runtime configuration for the web client.
 *
 * Cloud sync is opt-in: it runs only when the deploy sets `window.LCT_API_BASE`
 * to a string (see app-config.js, generated by `build:web` from the
 * LCT_API_BASE env var). Left undefined — the default for offline-only builds,
 * static hosting, and the test harness — the game stays purely local and makes
 * no network calls.
 *
 * Values: '' = same origin (the VPS that also serves the PWA); an absolute URL
 * (e.g. 'https://tycoon.example.com') for the packaged mobile apps, which have
 * no web origin of their own.
 */
/** True when the deploy has configured an API base (any string, incl. ''). */
export const SYNC_CONFIGURED = typeof window !== 'undefined' && typeof window.LCT_API_BASE === 'string';
export const API_BASE = SYNC_CONFIGURED ? window.LCT_API_BASE : '';
